// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCMcDiJPTwurW2jPvzh0loU0sKAlROXy0',
    appId: '1:22054797218:web:a4f4fa3a9666a044f67cfb',
    messagingSenderId: '22054797218',
    projectId: 'chat-app-635fc',
    authDomain: 'chat-app-635fc.firebaseapp.com',
    storageBucket: 'chat-app-635fc.appspot.com',
    measurementId: 'G-FED81SEFTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvMr0cMhUmHYPWuWIBpF4bBlHOYTJ41ik',
    appId: '1:22054797218:android:65a8173464e66f35f67cfb',
    messagingSenderId: '22054797218',
    projectId: 'chat-app-635fc',
    storageBucket: 'chat-app-635fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgVCkTvsXBiBIHhREg8M97EnXLs2BqMXQ',
    appId: '1:22054797218:ios:d73b29a497827d7ef67cfb',
    messagingSenderId: '22054797218',
    projectId: 'chat-app-635fc',
    storageBucket: 'chat-app-635fc.appspot.com',
    iosBundleId: 'com.flutter.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgVCkTvsXBiBIHhREg8M97EnXLs2BqMXQ',
    appId: '1:22054797218:ios:0938a1af9f2414d2f67cfb',
    messagingSenderId: '22054797218',
    projectId: 'chat-app-635fc',
    storageBucket: 'chat-app-635fc.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
